/*
 * This source file was generated by the Gradle 'init' task
 */
package bx.util;

import com.google.common.io.Closer;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;

public class Json {

  static tools.jackson.databind.ObjectMapper MAPPER = new ObjectMapper();

  public static ObjectMapper mapper() {
    return MAPPER;
  }

  public static JsonNode readTree(File f) {
    try (Closer c = Closer.create()) {

      FileInputStream fis = new FileInputStream(f);
      c.register(fis);
      return readTree(fis);
    } catch (IOException e) {
      throw new BxException(e);
    }
  }

  public static JsonNode readTree(String input) {

    return MAPPER.readTree(input);
  }

  public static JsonNode readTree(InputStream input) {

    return MAPPER.readTree(input);
  }

  public static JsonNode readTree(Reader input) {

    return MAPPER.readTree(input);
  }

  public static JsonNode readTree(byte[] input) {

    return MAPPER.readTree(input);
  }

  public static ObjectNode createObjectNode() {
    return MAPPER.createObjectNode();
  }

  public static ArrayNode createArrayNode() {
    return MAPPER.createArrayNode();
  }

  public static Stream<JsonNode> stream(JsonNode n) {
    if (n == null) {
      return Stream.empty();
    }
    return StreamSupport.stream(n.spliterator(), false);
  }
}
